### ISSUE TITLE
Update for API Version 4?

### ISSUE THREAD

**Issue by wwnpo01** [gwcottle/rcrunchbase#12]
Hi, I was checking out the package and I think it is really helpful. However, I would like to use it with the newest API Version. Unfortunately I did not manage to update it easily. Will there be an updated version?

**Comment by gwcottle** [comment]
I'm glad to hear it. I am planning to update the package for API v4.0, but it's not likely to happen before the fall. Currently Crunchbase plans to maintain v3.1 until Jan 29, 2021, and it will likely take me that long to update the package and work out the bugs. If you'd like to get started before then though feel free to fork a copy and give it a shot.

**Comment by wwnpo01** [comment]
Thanks for your fast answer! You are sure that they will keep v3.1 until january? Just asking because I got many html404 errors trying to crunchbase_get_details on many organizations I identified with crunchbase_get_collection("organizations")

Enviado desde Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by gwcottle** [comment]
Yes, I just pulled a list of 125 to make sure. If you're getting 404 errors check that the organization hasn't changed it's ID in Crunchbase. For example, cronofy is actually listed under the ID one-diary, so if I run crunchbase_get_collection("organizations/cronofy") it gives me a 404 error.

**Comment by wwnpo01** [comment]
Thank you, I will check it out 😊

**Comment by wwnpo01** [comment]
I tried to find out which IDs are correctly listed and which are not. This worked really well at the beginning, but when I tried to check more API paths, it seems that my code did not work any longer. That's what I tried: (I am not sure whether github is the correct place for these matters...)

>library("parallel")
>abc<- logical(1000) 
>websites <- organizations$properties.api_path[1:1000]

>Updated <- function(x){is.null(crunchbase_GET(x))}  
>cl <- makeCluster(detectCores(), type = "PSOCK")
>clusterExport(cl, varlist = "websites")
>clusterEvalQ(cl = cl, library(rcrunchbase))
>abc <- parSapply(cl = cl, X = websites, FUN = Updated, USE.NAMES = FALSE)

> abc[1000]
[1] TRUE
> websites[1000]
[1] "organizations/piccadily-sugar-allied-indus"
> crunchbase_GET("organizations/piccadily-sugar-allied-indus")
Response [https://api.crunchbase.com/v3.1/organizations/piccadily-sugar-allied-indus?user_key=...]
  Date: 2020-06-19 10:12
  Status: 200
  Content-Type: application/json; charset=utf-8
  Size: 10.4 kB

I was wondering it the problem could be related to the API limit though...

**Comment by gwcottle** [comment]
My approach would have been to been to just pull all the firm info into a single object and then manually check which which were missing from the list (I'm assuming that you're passing a list of firms to crunchbase_get_details). Sticking with your approach though if you're worried about the API limit you might be able to work in some of the code from rcrunchbase/R/managed-call.R

**Comment by gwcottle** [comment]
Update: Unfortunately I’m not in a position to update the package to the new API with all the changes that it requires. I added a note to readme.md explaining that it’s set to sunset on Jan. 29, 2021, when support for v3.1 ends. I attached documentation for contributors who want to update the package for API v4.0.
