### ISSUE TITLE
Vignette invested_in parts not working

### ISSUE THREAD

**Issue by yipcma** [gwcottle/rcrunchbase#3]
no invested_in dataframes are returned after calling crunchbase_expand_section(node, "investments").

**Comment by tarakc02** [comment]
Unfortunately, I don't think I can work on this until I've renewed my recently expired API key. I've submitted a request through the form on the webpage, but haven't heard any updates for several days. My fingers are crossed. If you are interested in working on the project, I'd be happy to accept a pull request.

**Comment by yipcma** [comment]
found the new one here https://github.com/tarakc02/rcrunchbase/blob/master/vignettes/getting-started.Rmd
