### ISSUE TITLE
single criteria categories for crunchbase_get_collection not working

### ISSUE THREAD

**Issue by yipcma** [gwcottle/rcrunchbase#4]
cooking <- crunchbase_get_collection("organizations", categories = "cooking")
2 pages in all, starting to download at 04:16:34 PM
.
Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match

**Comment by yipcma** [comment]
It seems to have something to do with there are extra columns in some pages than others. Would you please kindly check? Thanks a lot.

**Comment by yipcma** [comment]
ok after further testing, it seems you could fix it by using dplyr::bind_rows instead of rbind in the crunchbase_flatten. Please keep me posted.

**Comment by tarakc02** [comment]
Thanks for the help! I'm about to push the update. Feel free to submit a pull-request in the future. Note that I recently (last week) had my API key expire, and am working to get it renewed. But for now, it's difficult for me to test any changes I make, so I won't be able to do much for a little while.
