### ISSUE TITLE
Error installing rcrunchbase

### ISSUE THREAD

**Issue by ghost** [gwcottle/rcrunchbase#7]
Hi, I faced the following error while trying to install rcrunchbase from github, would you have any idea what I'm doing wrongly? Thanks!

> devtools::install_github("tarakc02/rcrunchbase")
> Downloading GitHub repo tarakc02/rcrunchbase@master
> from URL https://api.github.com/repos/tarakc02/rcrunchbase/zipball/master
> Installing rcrunchbase
> "E:/PROGRA~1/R-32~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD  \
>   INSTALL "E:/Temp/RtmpC6MBzy/devtools7f859755f56/tarakc02-rcrunchbase-8909714"  \
>   --library="E:/Users/User/Documents/R/win-library/3.2" --install-tests 
- installing _source_ package 'rcrunchbase' ...
  *\* R
  *\* inst
  *\* tests
  *\* preparing package for lazy loading
  Warning: replacing previous import by 'memoise::timeout' when loading 'rcrunchbase'
  Warning: replacing previous import by 'plyr::failwith' when loading 'rcrunchbase'
  Warning: replacing previous import by 'plyr::id' when loading 'rcrunchbase'
  Warning: replacing previous import by 'plyr::summarize' when loading 'rcrunchbase'
  Warning: replacing previous import by 'plyr::count' when loading 'rcrunchbase'
  Warning: replacing previous import by 'plyr::desc' when loading 'rcrunchbase'
  Warning: replacing previous import by 'plyr::mutate' when loading 'rcrunchbase'
  Warning: replacing previous import by 'plyr::arrange' when loading 'rcrunchbase'
  Warning: replacing previous import by 'plyr::rename' when loading 'rcrunchbase'
  Warning: replacing previous import by 'plyr::summarise' when loading 'rcrunchbase'
  Warning: replacing previous import by 'stringr::%>%' when loading 'rcrunchbase'
  Error in args(f) : could not find function "managed_call"
  Error : unable to load R code in package 'rcrunchbase'
  ERROR: lazy loading failed for package 'rcrunchbase'

**Comment by tarakc02** [comment]
Hmmn. I'm looking into it.

**Comment by tarakc02** [comment]
Hi @limxinyuuu, would you try installing now?

**Comment by ghost** [comment]
Thank you! It works now. However, I unable to parse any info (example below). Is there any way to correct this?

> gsw <- crunchbase_get_details("organization/golden-state-warriors")
> _.
> Warning messages:
> 1: HTTP failure: 404  
> 2: No output to parse 
> 
> x <- crunchbase_GET(c("person", "bill-gates"))
> Warning message:
> HTTP failure: 404  
> 
> crunchbase_parse(x)
> NULL
> Warning message:
> No output to parse

**Comment by tarakc02** [comment]
Hi @limxinyuuu I clearly need to update the vignette and other docs. You should do:

gsw <- crunchbase_get_details("organizations/golden-state-warriors")

They changed several of the endpoints, so now it's "organizations" instead of "organization" and "people" instead of "person" (as in crunchbase_get_details("people/bill-gates").

I'm working on some more thorough updates right now, hopefully they will make it easier to use and create less of the errors you're seeing. Thanks!
-T

**Comment by agogodavid** [comment]
Is the plugin broken after crunchbase upgraded to V3 of their API?
Here is the output I am getting from this command

`crunchbase_get_details("organizations/golden-state-warriors")`

It gives this error

```
_.list()
attr(,"class")
[1] "cb_nodes"
Warning messages:
1: HTTP failure: 401  
2: No output to parse 

```

**Comment by tarakc02** [comment]
Hi @agogodavid -- No, it works with v3. 401 is the "unauthorized" error code. Do you have advanced/commercial access? If not, then this query will not work. Try putting "golden-state-warriors" in here: https://data.crunchbase.com/docs/organization-permalink to see if you get the same response.

**Comment by agogodavid** [comment]
Thanks for your prompt reply
I did... it gave the same result and so I contacted Crunchbase. Here is their response.

> Thanks for reaching out. As we recently relaunched our Data Access plans, former userkeys had been suspended. You've now been reapproved for Research Access! You should receive an automated email with instructions later today. 

Thanks again.
